// Decompiled by Jad v1.5.8e2. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://kpdus.tripod.com/jad.html
// Decompiler options: packimports(3) fieldsfirst ansi space 
// Source File Name:   PrivilegeTest.java

package com.mulua.test;

import com.mulua.domain.system.Privilege;
import com.mulua.util.SpringUtils;
import org.hibernate.*;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public class PrivilegeTest extends SpringUtils
{

	public PrivilegeTest()
	{
	}

	public void testSavePrivilege_Menuitem()
	{
		ApplicationContext applicationContext = new ClassPathXmlApplicationContext("spring/applicationContext.xml");
		SessionFactory sessionFactory = (SessionFactory)applicationContext.getBean("sessionFactory");
		Session session = sessionFactory.openSession();
		Transaction transaction = session.beginTransaction();
		Privilege Privilegeitem1 = new Privilege();
		Privilegeitem1.setId(Long.valueOf(1L));
		Privilegeitem1.setIcon("css/images/MenuIcon/FUNC20082.gif");
		Privilegeitem1.setName("办公自动化");
		Privilegeitem1.setPid(Long.valueOf(0L));
		Privilegeitem1.setFlag("1");
		Privilegeitem1.setIsParent(Boolean.valueOf(true));
		Privilege Privilege2 = new Privilege();
		Privilege2.setId(Long.valueOf(2L));
		Privilege2.setIcon("css/images/MenuIcon/FUNC20001.gif");
		Privilege2.setName("个人办公");
		Privilege2.setPid(Long.valueOf(1L));
		Privilege2.setFlag("1");
		Privilege2.setIsParent(Boolean.valueOf(true));
		Privilege Privilege21 = new Privilege();
		Privilege21.setId(Long.valueOf(21L));
		Privilege21.setIcon("css/images/MenuIcon/FUNC20054.gif");
		Privilege21.setName("个人考勤");
		Privilege21.setPid(Long.valueOf(2L));
		Privilege21.setFlag("1");
		Privilege21.setIsParent(Boolean.valueOf(false));
		Privilege Privilege22 = new Privilege();
		Privilege22.setId(Long.valueOf(22L));
		Privilege22.setIcon("css/images/MenuIcon/FUNC23700.gif");
		Privilege22.setName("日程安排");
		Privilege22.setPid(Long.valueOf(2L));
		Privilege22.setFlag("1");
		Privilege22.setIsParent(Boolean.valueOf(false));
		Privilege Privilege23 = new Privilege();
		Privilege23.setId(Long.valueOf(23L));
		Privilege23.setIcon("css/images/MenuIcon/FUNC20069.gif");
		Privilege23.setName("工作计划");
		Privilege23.setPid(Long.valueOf(2L));
		Privilege23.setFlag("1");
		Privilege23.setIsParent(Boolean.valueOf(false));
		Privilege Privilege24 = new Privilege();
		Privilege24.setId(Long.valueOf(24L));
		Privilege24.setIcon("css/images/MenuIcon/FUNC20056.gif");
		Privilege24.setName("工作日记");
		Privilege24.setPid(Long.valueOf(2L));
		Privilege24.setFlag("1");
		Privilege24.setIsParent(Boolean.valueOf(false));
		Privilege Privilege25 = new Privilege();
		Privilege25.setId(Long.valueOf(25L));
		Privilege25.setIcon("css/images/MenuIcon/time_date.gif");
		Privilege25.setName("通讯录");
		Privilege25.setPid(Long.valueOf(2L));
		Privilege25.setFlag("1");
		Privilege25.setIsParent(Boolean.valueOf(false));
		Privilege Privilege3 = new Privilege();
		Privilege3.setId(Long.valueOf(3L));
		Privilege3.setIsParent(Boolean.valueOf(true));
		Privilege3.setPid(Long.valueOf(1L));
		Privilege3.setName("审批流转");
		Privilege3.setFlag("1");
		Privilege3.setIcon("css/images/MenuIcon/FUNC20057.gif");
		Privilege Privilege31 = new Privilege();
		Privilege31.setId(Long.valueOf(31L));
		Privilege31.setIsParent(Boolean.valueOf(false));
		Privilege31.setPid(Long.valueOf(3L));
		Privilege31.setName("审批流程管理");
		Privilege31.setIcon("css/images/MenuIcon/manager.gif");
		Privilege Privilege32 = new Privilege();
		Privilege32.setId(Long.valueOf(32L));
		Privilege32.setIsParent(Boolean.valueOf(false));
		Privilege32.setPid(Long.valueOf(3L));
		Privilege32.setName("表单模板管理");
		Privilege32.setIcon("css/images/MenuIcon/formmodel.gif");
		Privilege Privilege33 = new Privilege();
		Privilege33.setId(Long.valueOf(33L));
		Privilege33.setIsParent(Boolean.valueOf(false));
		Privilege33.setPid(Long.valueOf(3L));
		Privilege33.setName("发起申请");
		Privilege33.setIcon("css/images/MenuIcon/FUNC241000.gif");
		Privilege Privilege34 = new Privilege();
		Privilege34.setId(Long.valueOf(34L));
		Privilege34.setIsParent(Boolean.valueOf(false));
		Privilege34.setPid(Long.valueOf(3L));
		Privilege34.setName("审批申请");
		Privilege34.setIcon("css/images/MenuIcon/FUNC20029.gif");
		Privilege Privilege35 = new Privilege();
		Privilege35.setId(Long.valueOf(35L));
		Privilege35.setIsParent(Boolean.valueOf(false));
		Privilege35.setPid(Long.valueOf(3L));
		Privilege35.setName("状态查询");
		Privilege35.setIcon("css/images/MenuIcon/FUNC20029.gif");
		Privilege Privilege4 = new Privilege();
		Privilege4.setId(Long.valueOf(4L));
		Privilege4.setIsParent(Boolean.valueOf(false));
		Privilege4.setPid(Long.valueOf(1L));
		Privilege4.setName("知识管理");
		Privilege4.setIcon("css/images/MenuIcon/FUNC20056.gif");
		Privilege Privilege5 = new Privilege();
		Privilege5.setId(Long.valueOf(5L));
		Privilege5.setIsParent(Boolean.valueOf(true));
		Privilege5.setPid(Long.valueOf(1L));
		Privilege5.setName("管理行政");
		Privilege5.setIcon("css/images/MenuIcon/manager.gif");
		Privilege Privilege51 = new Privilege();
		Privilege51.setId(Long.valueOf(51L));
		Privilege51.setIsParent(Boolean.valueOf(false));
		Privilege51.setPid(Long.valueOf(5L));
		Privilege51.setName("考勤管理");
		Privilege51.setIcon("css/images/MenuIcon/FUNC20070.gif");
		Privilege Privilege52 = new Privilege();
		Privilege52.setId(Long.valueOf(52L));
		Privilege52.setIsParent(Boolean.valueOf(false));
		Privilege52.setPid(Long.valueOf(5L));
		Privilege52.setName("会议管理");
		Privilege52.setIcon("css/images/MenuIcon/FUNC20064.gif");
		Privilege Privilege53 = new Privilege();
		Privilege53.setId(Long.valueOf(53L));
		Privilege53.setIsParent(Boolean.valueOf(false));
		Privilege53.setPid(Long.valueOf(5L));
		Privilege53.setName("车辆管理");
		Privilege53.setIcon("css/images/MenuIcon/radio_blue.gif");
		Privilege Privilege6 = new Privilege();
		Privilege6.setId(Long.valueOf(6L));
		Privilege6.setIsParent(Boolean.valueOf(true));
		Privilege6.setPid(Long.valueOf(1L));
		Privilege6.setName("人力资源");
		Privilege6.setIcon("css/images/MenuIcon/FUNC20001.gif");
		Privilege Privilege61 = new Privilege();
		Privilege61.setId(Long.valueOf(61L));
		Privilege61.setIsParent(Boolean.valueOf(false));
		Privilege61.setPid(Long.valueOf(6L));
		Privilege61.setName("档案管理");
		Privilege61.setIcon("css/images/MenuIcon/FUNC20076.gif");
		Privilege Privilege62 = new Privilege();
		Privilege62.setId(Long.valueOf(62L));
		Privilege62.setIsParent(Boolean.valueOf(false));
		Privilege62.setPid(Long.valueOf(6L));
		Privilege62.setName("培训记录");
		Privilege62.setIcon("css/images/MenuIcon/FUNC55000.gif");
		Privilege Privilege63 = new Privilege();
		Privilege63.setId(Long.valueOf(63L));
		Privilege63.setIsParent(Boolean.valueOf(false));
		Privilege63.setPid(Long.valueOf(6L));
		Privilege63.setName("奖赏记录");
		Privilege63.setIcon("css/images/MenuIcon/FUNC55000.gif");
		Privilege Privilege64 = new Privilege();
		Privilege64.setId(Long.valueOf(64L));
		Privilege64.setIsParent(Boolean.valueOf(false));
		Privilege64.setPid(Long.valueOf(6L));
		Privilege64.setName("职位变更");
		Privilege64.setIcon("css/images/MenuIcon/FUNC55000.gif");
		Privilege Privilege65 = new Privilege();
		Privilege65.setId(Long.valueOf(65L));
		Privilege65.setIsParent(Boolean.valueOf(false));
		Privilege65.setPid(Long.valueOf(6L));
		Privilege65.setName("人事合同");
		Privilege65.setIcon("css/images/MenuIcon/FUNC55000.gif");
		Privilege Privilege66 = new Privilege();
		Privilege66.setId(Long.valueOf(66L));
		Privilege66.setIsParent(Boolean.valueOf(false));
		Privilege66.setPid(Long.valueOf(6L));
		Privilege66.setName("薪酬制度");
		Privilege66.setIcon("css/images/MenuIcon/FUNC20001.gif");
		Privilege Privilege7 = new Privilege();
		Privilege7.setId(Long.valueOf(7L));
		Privilege7.setIsParent(Boolean.valueOf(false));
		Privilege7.setPid(Long.valueOf(1L));
		Privilege7.setName("电子邮件");
		Privilege7.setIcon("css/images/MenuIcon/eml.gif");
		Privilege Privilege8 = new Privilege();
		Privilege8.setId(Long.valueOf(8L));
		Privilege8.setIsParent(Boolean.valueOf(true));
		Privilege8.setPid(Long.valueOf(1L));
		Privilege8.setName("实用工具");
		Privilege8.setIcon("css/images/MenuIcon/FUNC20076.gif");
		Privilege Privilege81 = new Privilege();
		Privilege81.setId(Long.valueOf(81L));
		Privilege81.setIsParent(Boolean.valueOf(false));
		Privilege81.setPid(Long.valueOf(8L));
		Privilege81.setName("车票预定");
		Privilege81.setIcon("css/images/MenuIcon/FUNC220000.gif");
		Privilege Privilege82 = new Privilege();
		Privilege82.setId(Long.valueOf(82L));
		Privilege82.setIsParent(Boolean.valueOf(false));
		Privilege82.setPid(Long.valueOf(8L));
		Privilege82.setName("GIS查询");
		Privilege82.setIcon("css/images/MenuIcon/search.gif");
		Privilege Privilege83 = new Privilege();
		Privilege83.setId(Long.valueOf(83L));
		Privilege83.setIsParent(Boolean.valueOf(false));
		Privilege83.setPid(Long.valueOf(8L));
		Privilege83.setName("邮政编码");
		Privilege83.setIcon("css/images/MenuIcon/FUNC249000.gif");
		Privilege Privilege9 = new Privilege();
		Privilege9.setId(Long.valueOf(9L));
		Privilege9.setIsParent(Boolean.valueOf(true));
		Privilege9.setPid(Long.valueOf(1L));
		Privilege9.setName("个人设置");
		Privilege9.setIcon("css/images/MenuIcon/FUNC20001.gif");
		Privilege Privilege91 = new Privilege();
		Privilege91.setId(Long.valueOf(91L));
		Privilege91.setIsParent(Boolean.valueOf(false));
		Privilege91.setPid(Long.valueOf(9L));
		Privilege91.setName("个人信息");
		Privilege91.setIcon("css/images/MenuIcon/FUNC20001.gif");
		Privilege Privilege92 = new Privilege();
		Privilege92.setId(Long.valueOf(92L));
		Privilege92.setIsParent(Boolean.valueOf(false));
		Privilege92.setPid(Long.valueOf(9L));
		Privilege92.setName("密码修改");
		Privilege92.setIcon("css/images/MenuIcon/FUNC241000.gif");
		Privilege Privilege10 = new Privilege();
		Privilege10.setId(Long.valueOf(10L));
		Privilege10.setIsParent(Boolean.valueOf(true));
		Privilege10.setPid(Long.valueOf(1L));
		Privilege10.setName("系统管理");
		Privilege10.setIcon("css/images/MenuIcon/system.gif");
		Privilege Privilege101 = new Privilege();
		Privilege101.setId(Long.valueOf(101L));
		Privilege101.setIsParent(Boolean.valueOf(false));
		Privilege101.setPid(Long.valueOf(10L));
		Privilege101.setName("岗位管理");
		Privilege101.setIcon("css/images/MenuIcon/FUNC20001.gif");
		Privilege Privilege102 = new Privilege();
		Privilege102.setId(Long.valueOf(102L));
		Privilege102.setIsParent(Boolean.valueOf(false));
		Privilege102.setPid(Long.valueOf(10L));
		Privilege102.setName("部门管理");
		Privilege102.setIcon("css/images/MenuIcon/department.gif");
		Privilege Privilege103 = new Privilege();
		Privilege103.setId(Long.valueOf(103L));
		Privilege103.setIsParent(Boolean.valueOf(false));
		Privilege103.setPid(Long.valueOf(10L));
		Privilege103.setName("用户管理");
		Privilege103.setIcon("css/images/MenuIcon/FUNC20001.gif");
		session.save(Privilegeitem1);
		session.save(Privilege2);
		session.save(Privilege21);
		session.save(Privilege22);
		session.save(Privilege23);
		session.save(Privilege24);
		session.save(Privilege25);
		session.save(Privilege3);
		session.save(Privilege31);
		session.save(Privilege32);
		session.save(Privilege33);
		session.save(Privilege34);
		session.save(Privilege35);
		session.save(Privilege4);
		session.save(Privilege5);
		session.save(Privilege51);
		session.save(Privilege52);
		session.save(Privilege53);
		session.save(Privilege6);
		session.save(Privilege61);
		session.save(Privilege62);
		session.save(Privilege63);
		session.save(Privilege64);
		session.save(Privilege65);
		session.save(Privilege66);
		session.save(Privilege7);
		session.save(Privilege8);
		session.save(Privilege81);
		session.save(Privilege82);
		session.save(Privilege83);
		session.save(Privilege9);
		session.save(Privilege91);
		session.save(Privilege92);
		session.save(Privilege10);
		session.save(Privilege101);
		session.save(Privilege102);
		session.save(Privilege103);
		transaction.commit();
		session.close();
	}

	public void testSavePrivilege_Function()
	{
		ApplicationContext applicationContext = new ClassPathXmlApplicationContext("spring/applicationContext.xml");
		SessionFactory sessionFactory = (SessionFactory)applicationContext.getBean("sessionFactory");
		Session session = sessionFactory.openSession();
		Transaction transaction = session.beginTransaction();
		Privilege Privilege1 = new Privilege();
		Privilege1.setId(Long.valueOf(201L));
		Privilege1.setFlag("2");
		Privilege1.setPid(Long.valueOf(0L));
		Privilege1.setIcon("css/images/MenuIcon/system.gif");
		Privilege1.setName("用户增加");
		Privilege Privilege2 = new Privilege();
		Privilege2.setId(Long.valueOf(202L));
		Privilege2.setFlag("2");
		Privilege2.setPid(Long.valueOf(0L));
		Privilege2.setIcon("css/images/MenuIcon/system.gif");
		Privilege2.setName("用户删除");
		Privilege Privilege3 = new Privilege();
		Privilege3.setId(Long.valueOf(203L));
		Privilege3.setFlag("2");
		Privilege3.setPid(Long.valueOf(0L));
		Privilege3.setIcon("css/images/MenuIcon/system.gif");
		Privilege3.setName("用户修改");
		Privilege Privilege4 = new Privilege();
		Privilege4.setId(Long.valueOf(204L));
		Privilege4.setFlag("2");
		Privilege4.setPid(Long.valueOf(0L));
		Privilege4.setIcon("css/images/MenuIcon/system.gif");
		Privilege4.setName("部门增加");
		Privilege Privilege5 = new Privilege();
		Privilege5.setId(Long.valueOf(205L));
		Privilege5.setFlag("2");
		Privilege5.setPid(Long.valueOf(0L));
		Privilege5.setIcon("css/images/MenuIcon/system.gif");
		Privilege5.setName("部门删除");
		Privilege Privilege6 = new Privilege();
		Privilege6.setId(Long.valueOf(206L));
		Privilege6.setFlag("2");
		Privilege6.setPid(Long.valueOf(0L));
		Privilege6.setIcon("css/images/MenuIcon/system.gif");
		Privilege6.setName("部门修改");
		Privilege Privilege7 = new Privilege();
		Privilege7.setId(Long.valueOf(207L));
		Privilege7.setFlag("2");
		Privilege7.setPid(Long.valueOf(0L));
		Privilege7.setIcon("css/images/MenuIcon/system.gif");
		Privilege7.setName("岗位增加");
		Privilege Privilege8 = new Privilege();
		Privilege8.setId(Long.valueOf(208L));
		Privilege8.setFlag("2");
		Privilege8.setPid(Long.valueOf(0L));
		Privilege8.setIcon("css/images/MenuIcon/system.gif");
		Privilege8.setName("岗位删除");
		Privilege Privilege9 = new Privilege();
		Privilege9.setId(Long.valueOf(209L));
		Privilege9.setFlag("2");
		Privilege9.setPid(Long.valueOf(0L));
		Privilege9.setIcon("css/images/MenuIcon/system.gif");
		Privilege9.setName("岗位修改");
		session.save(Privilege1);
		session.save(Privilege2);
		session.save(Privilege3);
		session.save(Privilege4);
		session.save(Privilege5);
		session.save(Privilege6);
		session.save(Privilege7);
		session.save(Privilege8);
		session.save(Privilege9);
		transaction.commit();
		session.close();
	}
}
